# file: roles/redis/tasks/main.yml
---

- name: install redis
  apt: pkg=redis-server state=installed

- name: ensure redis is started on ubuntu 14
  service: name=redis-server state=started

- name: set redis port
  lineinfile: dest=/etc/redis/redis.conf regexp="^port = " insertafter="^port = " line="port {{ redis_port }}"